import Head from 'next/head'
import Image from 'next/image'
import Banner from "../components/banner"
import SelectRole from "../components/selectRole"

export default function Home() {
  return (
    <div>
      <Head>
        <title>eMentorHub - A powerful platform for growth and mentorship at your fingertips</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Banner/>
        <SelectRole/>
      </main>
    </div>
  )
}
